public enum ChallengeObjectiveTypeSCore : byte {
    ChallengeObjectiveEnterPOI= 100,
    ChallengeObjectiveCompleteQuestStealth = 101,
    ChallengeObjectiveKillWithItem = 102,
    ChallengeObjectiveStealthKillStreak= 103,
    ChallengeObjectiveDecapitation= 104,
    ChallengeObjectiveCraftWithIngredient= 105,
    ChallengeObjectiveBlockDestroyedByFire= 106,
    ChallengeObjectiveBlockDestroyed= 107,
    ChallengeObjectiveStartFire= 108,
    ChallengeObjectiveBigFire= 109,
    ChallengeObjectiveExtinguishFire= 110,
    ChallengeObjectiveHireNPC =111,
    ChallengeObjectiveHarvest=112,
    ChallengeObjectiveBlockUpgradeSCore=113,
    ChallengeObjectiveGatherTags=114,
    ChallengeObjectiveWearTags=115,
    ChallengeObjectiveCVar=116,
    ChallengeObjectiveCraftWithTags=117,
    ChallengeObjectivePlaceBlockByTag=118,
    ChallengeObjectiveClearSleepers=119,
    ChallengeObjectiveKillV2=120,
    ChallengeObjectiveHarvestV2=122,
    ChallengeObjectivePlaceBlockByTagV2=123,
    ChallengeObjectiveCVarV2 = 124
}