var annotated_dup =
[
    [ "BlockMortSpawner", "d9/d66/class_block_mort_spawner.html", "d9/d66/class_block_mort_spawner" ],
    [ "BlockMusicBox", "d3/dcc/class_block_music_box.html", "d3/dcc/class_block_music_box" ],
    [ "BlockPoweredWorkstationSDX", "d2/d9b/class_block_powered_workstation_s_d_x.html", "d2/d9b/class_block_powered_workstation_s_d_x" ],
    [ "BlockTakeAndReplace", "de/dc5/class_block_take_and_replace.html", "de/dc5/class_block_take_and_replace" ],
    [ "BlockTriggeredSDX", "d7/d9c/class_block_triggered_s_d_x.html", "d7/d9c/class_block_triggered_s_d_x" ],
    [ "ClearUI", "db/dcb/class_clear_u_i.html", [
      [ "ClearUI_Init", "d5/dec/class_clear_u_i_1_1_clear_u_i___init.html", "d5/dec/class_clear_u_i_1_1_clear_u_i___init" ],
      [ "SphereII_ClearUI_ItemActionAttack", "db/da4/class_clear_u_i_1_1_sphere_i_i___clear_u_i___item_action_attack.html", null ],
      [ "SphereII_ClearUI_ItemActionDynamic", "d2/daf/class_clear_u_i_1_1_sphere_i_i___clear_u_i___item_action_dynamic.html", null ],
      [ "SphereII_ClearUI_ItemActionDynamicMeLee", "d6/d12/class_clear_u_i_1_1_sphere_i_i___clear_u_i___item_action_dynamic_me_lee.html", null ],
      [ "SphereII_ClearUI_ItemActionRanged", "de/d63/class_clear_u_i_1_1_sphere_i_i___clear_u_i___item_action_ranged.html", null ],
      [ "SphereII_ClearUI_ItemActionUseOther", "d3/d09/class_clear_u_i_1_1_sphere_i_i___clear_u_i___item_action_use_other.html", null ],
      [ "SphereII_ClearUI_ItemClass_Crosshair", "d3/d9a/class_clear_u_i_1_1_sphere_i_i___clear_u_i___item_class___crosshair.html", null ],
      [ "SphereII_ClearUI_NGuiWdwInGameHUD", "de/dc4/class_clear_u_i_1_1_sphere_i_i___clear_u_i___n_gui_wdw_in_game_h_u_d.html", null ],
      [ "SphereII_ClearUI_NGUIWindowManager", "da/da8/class_clear_u_i_1_1_sphere_i_i___clear_u_i___n_g_u_i_window_manager.html", null ],
      [ "SphereII_ClearUI_NGUIWindowManager_SetLabelText", "dc/d01/class_clear_u_i_1_1_sphere_i_i___clear_u_i___n_g_u_i_window_manager___set_label_text.html", null ],
      [ "SphereII_ClearUI_NotifyDamageMultiplier", "d0/da2/class_clear_u_i_1_1_sphere_i_i___clear_u_i___notify_damage_multiplier.html", null ],
      [ "SphereII_ClearUI_NotifySneakDamage", "d4/d42/class_clear_u_i_1_1_sphere_i_i___clear_u_i___notify_sneak_damage.html", null ],
      [ "SphereII_ClearUI_SetTooltipText", "da/dfa/class_clear_u_i_1_1_sphere_i_i___clear_u_i___set_tooltip_text.html", null ],
      [ "SphereII_ClearUI_StealthScreenOverlay", "dc/d9d/class_clear_u_i_1_1_sphere_i_i___clear_u_i___stealth_screen_overlay.html", null ],
      [ "SphereII_ClearUI_XUiC_CompassWindow", "da/d3e/class_clear_u_i_1_1_sphere_i_i___clear_u_i___x_ui_c___compass_window.html", null ],
      [ "SphereII_ClearUI_XUiC_Timer_OnOpen", "d5/d34/class_clear_u_i_1_1_sphere_i_i___clear_u_i___x_ui_c___timer___on_open.html", null ],
      [ "SphereII_ClearUI_XUiC_TipWindow", "d7/d61/class_clear_u_i_1_1_sphere_i_i___clear_u_i___x_ui_c___tip_window.html", null ]
    ] ],
    [ "DialogActionAddCVar", "d8/dd5/class_dialog_action_add_c_var.html", "d8/dd5/class_dialog_action_add_c_var" ],
    [ "DialogActionExecuteCommandSDX", "db/d3c/class_dialog_action_execute_command_s_d_x.html", "db/d3c/class_dialog_action_execute_command_s_d_x" ],
    [ "DialogActionGetItemSDX", "d3/d6f/class_dialog_action_get_item_s_d_x.html", "d3/d6f/class_dialog_action_get_item_s_d_x" ],
    [ "DialogActionGiveQuestSDX", "d6/de6/class_dialog_action_give_quest_s_d_x.html", "d6/de6/class_dialog_action_give_quest_s_d_x" ],
    [ "DialogActionGiveToNPC", "d9/d92/class_dialog_action_give_to_n_p_c.html", "d9/d92/class_dialog_action_give_to_n_p_c" ],
    [ "DialogActionOpenDialogSDX", "dc/da7/class_dialog_action_open_dialog_s_d_x.html", "dc/da7/class_dialog_action_open_dialog_s_d_x" ],
    [ "DialogActionOpenWindowSDX", "d6/d36/class_dialog_action_open_window_s_d_x.html", "d6/d36/class_dialog_action_open_window_s_d_x" ],
    [ "DialogActionRemoveBuffSDX", "d7/db9/class_dialog_action_remove_buff_s_d_x.html", "d7/db9/class_dialog_action_remove_buff_s_d_x" ],
    [ "DialogActionRewardSkillPoint", "df/dc8/class_dialog_action_reward_skill_point.html", "df/dc8/class_dialog_action_reward_skill_point" ],
    [ "DialogActionShowToolTipSDX", "d5/d72/class_dialog_action_show_tool_tip_s_d_x.html", "d5/d72/class_dialog_action_show_tool_tip_s_d_x" ],
    [ "DialogRequirementHasBuffSDX", "d8/d87/class_dialog_requirement_has_buff_s_d_x.html", "d8/d87/class_dialog_requirement_has_buff_s_d_x" ],
    [ "DialogRequirementHasCompletedQuestSDX", "df/d8f/class_dialog_requirement_has_completed_quest_s_d_x.html", "df/d8f/class_dialog_requirement_has_completed_quest_s_d_x" ],
    [ "DialogRequirementHasCVarSDX", "d8/d82/class_dialog_requirement_has_c_var_s_d_x.html", "d8/d82/class_dialog_requirement_has_c_var_s_d_x" ],
    [ "DialogRequirementHasFailedQuestSDX", "d2/dc1/class_dialog_requirement_has_failed_quest_s_d_x.html", "d2/dc1/class_dialog_requirement_has_failed_quest_s_d_x" ],
    [ "DialogRequirementHasItemSDX", "d4/d77/class_dialog_requirement_has_item_s_d_x.html", "d4/d77/class_dialog_requirement_has_item_s_d_x" ],
    [ "DialogRequirementHasQuestSDX", "df/dad/class_dialog_requirement_has_quest_s_d_x.html", "df/dad/class_dialog_requirement_has_quest_s_d_x" ],
    [ "DialogRequirementHasTaskSDX", "d1/de5/class_dialog_requirement_has_task_s_d_x.html", "d1/de5/class_dialog_requirement_has_task_s_d_x" ],
    [ "DialogRequirementHiredSDX", "d8/d4e/class_dialog_requirement_hired_s_d_x.html", "d8/d4e/class_dialog_requirement_hired_s_d_x" ],
    [ "DialogRequirementPatrolSDX", "df/dfa/class_dialog_requirement_patrol_s_d_x.html", "df/dfa/class_dialog_requirement_patrol_s_d_x" ],
    [ "EAIApproachAndAttackSDX", "da/d93/class_e_a_i_approach_and_attack_s_d_x.html", "da/d93/class_e_a_i_approach_and_attack_s_d_x" ],
    [ "EAIApproachAndFollowTargetSDX", "d8/d59/class_e_a_i_approach_and_follow_target_s_d_x.html", "d8/d59/class_e_a_i_approach_and_follow_target_s_d_x" ],
    [ "EAIGuardSDX", "d1/dd8/class_e_a_i_guard_s_d_x.html", "d1/dd8/class_e_a_i_guard_s_d_x" ],
    [ "EAILootLocationSDX", "d0/d8c/class_e_a_i_loot_location_s_d_x.html", "d0/d8c/class_e_a_i_loot_location_s_d_x" ],
    [ "EAIMaslowLevel1SDX", "dc/db8/class_e_a_i_maslow_level1_s_d_x.html", "dc/db8/class_e_a_i_maslow_level1_s_d_x" ],
    [ "EAIPatrolSDX", "de/dd5/class_e_a_i_patrol_s_d_x.html", "de/dd5/class_e_a_i_patrol_s_d_x" ],
    [ "EAIRunAwayFromEntitySDX", "d7/d71/class_e_a_i_run_away_from_entity_s_d_x.html", "d7/d71/class_e_a_i_run_away_from_entity_s_d_x" ],
    [ "EAISetAsTargetIfHurtSDX", "df/d42/class_e_a_i_set_as_target_if_hurt_s_d_x.html", "df/d42/class_e_a_i_set_as_target_if_hurt_s_d_x" ],
    [ "EAISetAsTargetIfLeaderAttackedSDX", "d3/d4f/class_e_a_i_set_as_target_if_leader_attacked_s_d_x.html", "d3/d4f/class_e_a_i_set_as_target_if_leader_attacked_s_d_x" ],
    [ "EAISetAsTargetNearestEnemySDX", "d6/dd2/class_e_a_i_set_as_target_nearest_enemy_s_d_x.html", "d6/dd2/class_e_a_i_set_as_target_nearest_enemy_s_d_x" ],
    [ "EAITaskPatches", "d5/d0f/class_e_a_i_task_patches.html", "d5/d0f/class_e_a_i_task_patches" ],
    [ "EAIWanderSDX", "dd/dda/class_e_a_i_wander_s_d_x.html", "dd/dda/class_e_a_i_wander_s_d_x" ],
    [ "EntityAliveEventSpawnerSDX", "d6/dc8/class_entity_alive_event_spawner_s_d_x.html", "d6/dc8/class_entity_alive_event_spawner_s_d_x" ],
    [ "EntityAliveFarmingAnimalSDX", "d4/de6/class_entity_alive_farming_animal_s_d_x.html", "d4/de6/class_entity_alive_farming_animal_s_d_x" ],
    [ "EntityAliveSDX", "dc/dd7/class_entity_alive_s_d_x.html", "dc/dd7/class_entity_alive_s_d_x" ],
    [ "EntityAliveSDXPatcher", "dc/d8b/class_entity_alive_s_d_x_patcher.html", "dc/d8b/class_entity_alive_s_d_x_patcher" ],
    [ "EntityBanditSDX", "d5/da5/class_entity_bandit_s_d_x.html", "d5/da5/class_entity_bandit_s_d_x" ],
    [ "EntityFlyingBaseSDX", "d7/de7/class_entity_flying_base_s_d_x.html", "d7/de7/class_entity_flying_base_s_d_x" ],
    [ "EntityGenericSDX", "de/dd4/class_entity_generic_s_d_x.html", "de/dd4/class_entity_generic_s_d_x" ],
    [ "EntityMoveHelperSDX", "da/d35/class_entity_move_helper_s_d_x.html", "da/d35/class_entity_move_helper_s_d_x" ],
    [ "EntityNPCGreetingFix", "db/d51/class_entity_n_p_c_greeting_fix.html", "db/d51/class_entity_n_p_c_greeting_fix" ],
    [ "EntityNPCMakeVulnerable", "d3/df9/class_entity_n_p_c_make_vulnerable.html", "d3/df9/class_entity_n_p_c_make_vulnerable" ],
    [ "EntityNPCSpeedFix", "d6/d35/class_entity_n_p_c_speed_fix.html", "d6/d35/class_entity_n_p_c_speed_fix" ],
    [ "EntityPlayerSDX", "d4/d84/class_entity_player_s_d_x.html", "d4/d84/class_entity_player_s_d_x" ],
    [ "EntityPlayerSDXLocal", "d4/d4d/class_entity_player_s_d_x_local.html", "d4/d4d/class_entity_player_s_d_x_local" ],
    [ "EntitySurvivorSDX", "de/d89/class_entity_survivor_s_d_x.html", "de/d89/class_entity_survivor_s_d_x" ],
    [ "EntitySwimingSDX", "d7/d75/class_entity_swiming_s_d_x.html", "d7/d75/class_entity_swiming_s_d_x" ],
    [ "EntityWanderingTrader", "dc/dac/class_entity_wandering_trader.html", "dc/dac/class_entity_wandering_trader" ],
    [ "EntityZombieCopSDX", "da/ded/class_entity_zombie_cop_s_d_x.html", "da/ded/class_entity_zombie_cop_s_d_x" ],
    [ "EntityZombieCrawlSDX", "de/d80/class_entity_zombie_crawl_s_d_x.html", "de/d80/class_entity_zombie_crawl_s_d_x" ],
    [ "EntityZombieFlockSDX", "d9/db9/class_entity_zombie_flock_s_d_x.html", "d9/db9/class_entity_zombie_flock_s_d_x" ],
    [ "EntityZombieFlyingSDX", "d1/d2b/class_entity_zombie_flying_s_d_x.html", "d1/d2b/class_entity_zombie_flying_s_d_x" ],
    [ "FoodSpoilage_Mod", "de/d71/class_food_spoilage___mod.html", "de/d71/class_food_spoilage___mod" ],
    [ "FoodSpoilagePatch", "df/df5/class_food_spoilage_patch.html", "df/df5/class_food_spoilage_patch" ],
    [ "ItemActionEntryResharpenSDX", "d7/dae/class_item_action_entry_resharpen_s_d_x.html", "d7/dae/class_item_action_entry_resharpen_s_d_x" ],
    [ "MecanimSDX", "d0/dd8/class_mecanim_s_d_x.html", "d0/dd8/class_mecanim_s_d_x" ],
    [ "MinEventActionAddBuffByFactionSDX", "d4/d84/class_min_event_action_add_buff_by_faction_s_d_x.html", "d4/d84/class_min_event_action_add_buff_by_faction_s_d_x" ],
    [ "MinEventActionAnimatorSpeedSDX", "d8/ded/class_min_event_action_animator_speed_s_d_x.html", "d8/ded/class_min_event_action_animator_speed_s_d_x" ],
    [ "MinEventActionCreateItemSDX", "d9/d0f/class_min_event_action_create_item_s_d_x.html", "d9/d0f/class_min_event_action_create_item_s_d_x" ],
    [ "MinEventActionGiveQuestSDX", "d2/d75/class_min_event_action_give_quest_s_d_x.html", "d2/d75/class_min_event_action_give_quest_s_d_x" ],
    [ "MinEventActionModifySkillSDX", "d1/ddd/class_min_event_action_modify_skill_s_d_x.html", "d1/ddd/class_min_event_action_modify_skill_s_d_x" ],
    [ "MinEventActionNotifyTeamAttack", "d2/d72/class_min_event_action_notify_team_attack.html", "d2/d72/class_min_event_action_notify_team_attack" ],
    [ "MinEventActionPlayerLevelSDX", "de/db3/class_min_event_action_player_level_s_d_x.html", "de/db3/class_min_event_action_player_level_s_d_x" ],
    [ "MinEventActionPumpQuestSDX", "d9/d25/class_min_event_action_pump_quest_s_d_x.html", "d9/d25/class_min_event_action_pump_quest_s_d_x" ],
    [ "MinEventActionShowToolTipSDX", "d2/d22/class_min_event_action_show_tool_tip_s_d_x.html", "d2/d22/class_min_event_action_show_tool_tip_s_d_x" ],
    [ "MinEventActionSkillPointSDX", "d0/ddb/class_min_event_action_skill_point_s_d_x.html", "d0/ddb/class_min_event_action_skill_point_s_d_x" ],
    [ "MinEventActionSpawnBabySDX", "d5/d08/class_min_event_action_spawn_baby_s_d_x.html", null ],
    [ "MinEventActionSpawnEntitySDX", "de/d8f/class_min_event_action_spawn_entity_s_d_x.html", "de/d8f/class_min_event_action_spawn_entity_s_d_x" ],
    [ "MinEventActionToggleCamera", "db/d83/class_min_event_action_toggle_camera.html", "db/d83/class_min_event_action_toggle_camera" ],
    [ "MortSpawnerScript", "dd/d50/class_mort_spawner_script.html", "dd/d50/class_mort_spawner_script" ],
    [ "MusicBoxScript", "d6/deb/class_music_box_script.html", "d6/deb/class_music_box_script" ],
    [ "New_EAIMaslowLevel1SDX", "d5/d8f/class_new___e_a_i_maslow_level1_s_d_x.html", "d5/d8f/class_new___e_a_i_maslow_level1_s_d_x" ],
    [ "ObjectiveBuffSDX", "d1/d4c/class_objective_buff_s_d_x.html", "d1/d4c/class_objective_buff_s_d_x" ],
    [ "ObjectiveGotoPOISDX", "d0/d27/class_objective_goto_p_o_i_s_d_x.html", "d0/d27/class_objective_goto_p_o_i_s_d_x" ],
    [ "QuestActionGiveBuffSDX", "dd/d37/class_quest_action_give_buff_s_d_x.html", "dd/d37/class_quest_action_give_buff_s_d_x" ],
    [ "QuestActionGiveCVarBuffSDX", "dc/d57/class_quest_action_give_c_var_buff_s_d_x.html", "dc/d57/class_quest_action_give_c_var_buff_s_d_x" ],
    [ "QuestActionPlaySoundSDX", "d7/dd3/class_quest_action_play_sound_s_d_x.html", "d7/dd3/class_quest_action_play_sound_s_d_x" ],
    [ "QuestActionReplaceEntitySDX", "de/de6/class_quest_action_replace_entity_s_d_x.html", "de/de6/class_quest_action_replace_entity_s_d_x" ],
    [ "QuestActionSpawnEntitySDX", "d9/db1/class_quest_action_spawn_entity_s_d_x.html", "d9/db1/class_quest_action_spawn_entity_s_d_x" ],
    [ "RequirementEveryDawn", "df/d2c/class_requirement_every_dawn.html", "df/d2c/class_requirement_every_dawn" ],
    [ "RequirementEveryXDaySDX", "d4/d94/class_requirement_every_x_day_s_d_x.html", "d4/d94/class_requirement_every_x_day_s_d_x" ],
    [ "RequirementEveryXHourSDX", "d2/d94/class_requirement_every_x_hour_s_d_x.html", "d2/d94/class_requirement_every_x_hour_s_d_x" ],
    [ "RequirementOnSpecificBiomeSDX", "dc/d2c/class_requirement_on_specific_biome_s_d_x.html", "dc/d2c/class_requirement_on_specific_biome_s_d_x" ],
    [ "RequirementSameFactionSDX", "d8/dd0/class_requirement_same_faction_s_d_x.html", "d8/dd0/class_requirement_same_faction_s_d_x" ],
    [ "RewardGiveNPCSDX", "d2/d79/class_reward_give_n_p_c_s_d_x.html", "d2/d79/class_reward_give_n_p_c_s_d_x" ],
    [ "RewardItemSDX", "dd/d4c/class_reward_item_s_d_x.html", "dd/d4c/class_reward_item_s_d_x" ],
    [ "RewardQuestSDX", "df/da0/class_reward_quest_s_d_x.html", "df/da0/class_reward_quest_s_d_x" ],
    [ "RewardReassignNPCSDX", "d9/d6a/class_reward_reassign_n_p_c_s_d_x.html", "d9/d6a/class_reward_reassign_n_p_c_s_d_x" ],
    [ "SDXDialog", "d1/db8/class_s_d_x_dialog.html", "d1/db8/class_s_d_x_dialog" ],
    [ "SphereII__AdvancedItems", "d8/d36/class_sphere_i_i_____advanced_items.html", "d8/d36/class_sphere_i_i_____advanced_items" ],
    [ "SphereII__AdvancedItems_DurabilityAffectsDamagey", "d5/da2/class_sphere_i_i_____advanced_items___durability_affects_damagey.html", "d5/da2/class_sphere_i_i_____advanced_items___durability_affects_damagey" ],
    [ "SphereII__EntityAlivePatcher", "d0/d68/class_sphere_i_i_____entity_alive_patcher.html", "d0/d68/class_sphere_i_i_____entity_alive_patcher" ],
    [ "SphereII__OneBlockCrouch", "d0/d60/class_sphere_i_i_____one_block_crouch.html", "d0/d60/class_sphere_i_i_____one_block_crouch" ],
    [ "SphereII__SoftHands", "d9/d9c/class_sphere_i_i_____soft_hands.html", "d9/d9c/class_sphere_i_i_____soft_hands" ],
    [ "SphereII_Audio_Client_Play_1", "db/dde/class_sphere_i_i___audio___client___play__1.html", null ],
    [ "SphereII_Audio_Client_Play_2", "de/d9b/class_sphere_i_i___audio___client___play__2.html", null ],
    [ "SphereII_Audio_Manager_Play", "d3/d36/class_sphere_i_i___audio___manager___play.html", null ],
    [ "SphereII_Audio_Server_Play", "df/de4/class_sphere_i_i___audio___server___play.html", null ],
    [ "SphereII_AvatarController", "d8/d22/class_sphere_i_i___avatar_controller.html", [
      [ "SphereII_AnimatorMapperTrigger", "d5/d96/class_sphere_i_i___avatar_controller_1_1_sphere_i_i___animator_mapper_trigger.html", null ]
    ] ],
    [ "SphereII_DialogFromXML_Extensions", "da/d67/class_sphere_i_i___dialog_from_x_m_l___extensions.html", [
      [ "SphereII__DialogFromXML_ParseAction", "d6/d67/class_sphere_i_i___dialog_from_x_m_l___extensions_1_1_sphere_i_i_____dialog_from_x_m_l___parse_action.html", null ],
      [ "SphereII__DialogFromXML_ParseRequirement", "d5/dc1/class_sphere_i_i___dialog_from_x_m_l___extensions_1_1_sphere_i_i_____dialog_from_x_m_l___parse_requirement.html", null ]
    ] ],
    [ "SphereII_EAIApproachAndAttackTarget", "da/d52/class_sphere_i_i___e_a_i_approach_and_attack_target.html", [
      [ "SphereII_EAIApproachAndAttackTarget_CanExecute", "dc/d0b/class_sphere_i_i___e_a_i_approach_and_attack_target_1_1_sphere_i_i___e_a_i_approach_and_attack_target___can_execute.html", null ],
      [ "SphereII_EAIApproachAndAttackTarget_Continue", "d2/db9/class_sphere_i_i___e_a_i_approach_and_attack_target_1_1_sphere_i_i___e_a_i_approach_and_attack_target___continue.html", null ],
      [ "SphereII_EAIApproachAndAttackTarget_Helper", "db/d91/class_sphere_i_i___e_a_i_approach_and_attack_target_1_1_sphere_i_i___e_a_i_approach_and_attack_target___helper.html", null ]
    ] ],
    [ "SphereII_EAISetAsTargetHurt_Leader_Protect", "de/deb/class_sphere_i_i___e_a_i_set_as_target_hurt___leader___protect.html", [
      [ "SphereII_EAIApproachAndAttackTarget_CanExecute", "d6/d0c/class_sphere_i_i___e_a_i_set_as_target_hurt___leader___protect_1_1_sphere_i_i___e_a_i_approach_and_attack_target___can_execute.html", null ]
    ] ],
    [ "SphereII_EModelBase_InitCommon", "d1/d26/class_sphere_i_i___e_model_base___init_common.html", null ],
    [ "SphereII_EntityAliveStartingEquipment_Equiment", "d1/dd8/class_sphere_i_i___entity_alive_starting_equipment___equiment.html", [
      [ "SphereII__EntityAliveStartingEquipment_PostInit", "de/db9/class_sphere_i_i___entity_alive_starting_equipment___equiment_1_1_sphere_i_i_____entity_alive_starting_equipment___post_init.html", null ]
    ] ],
    [ "SphereII_EntityFactoryPatch", "d6/dd6/class_sphere_i_i___entity_factory_patch.html", null ],
    [ "SphereII_GiveBuffOrQuestBySound", "d9/dee/class_sphere_i_i___give_buff_or_quest_by_sound.html", null ],
    [ "SphereII_HeadshotOnly", "d9/dcd/class_sphere_i_i___headshot_only.html", "d9/dcd/class_sphere_i_i___headshot_only" ],
    [ "SphereII_InertEntity", "d6/d47/class_sphere_i_i___inert_entity.html", "d6/d47/class_sphere_i_i___inert_entity" ],
    [ "SphereII_LegacyDistantTerrain", "d5/d23/class_sphere_i_i___legacy_distant_terrain.html", [
      [ "SphereII_GameManager_SplatMap", "de/d4d/class_sphere_i_i___legacy_distant_terrain_1_1_sphere_i_i___game_manager___splat_map.html", null ],
      [ "SphereII_LegacyDistantTerrain_Init", "d5/de3/class_sphere_i_i___legacy_distant_terrain_1_1_sphere_i_i___legacy_distant_terrain___init.html", "d5/de3/class_sphere_i_i___legacy_distant_terrain_1_1_sphere_i_i___legacy_distant_terrain___init" ],
      [ "SphereII_VoxelMeshTerrain_Update", "d6/d32/class_sphere_i_i___legacy_distant_terrain_1_1_sphere_i_i___voxel_mesh_terrain___update.html", null ],
      [ "SphereII_WorldEnvironment_Cleanup", "d1/dbd/class_sphere_i_i___legacy_distant_terrain_1_1_sphere_i_i___world_environment___cleanup.html", null ],
      [ "SphereII_WorldEnvironment_CreateDistantTerrain", "da/d52/class_sphere_i_i___legacy_distant_terrain_1_1_sphere_i_i___world_environment___create_distant_terrain.html", null ],
      [ "SphereII_WorldEnvironment_OnChunkDisplayed", "da/ddc/class_sphere_i_i___legacy_distant_terrain_1_1_sphere_i_i___world_environment___on_chunk_displayed.html", null ]
    ] ],
    [ "SphereII_LowerResolutionUMA", "d5/dfc/class_sphere_i_i___lower_resolution_u_m_a.html", "d5/dfc/class_sphere_i_i___lower_resolution_u_m_a" ],
    [ "SphereII_NerdPoll", "d1/d3e/class_sphere_i_i___nerd_poll.html", null ],
    [ "SphereII_NoExceptionHijack", "d8/dc2/class_sphere_i_i___no_exception_hijack.html", "d8/dc2/class_sphere_i_i___no_exception_hijack" ],
    [ "SphereII_NPCFeatures_EntityAttention", "d2/d34/class_sphere_i_i___n_p_c_features___entity_attention.html", [
      [ "SphereII_NPCFeatures_EntityAttention_OnUpdateLive", "de/d76/class_sphere_i_i___n_p_c_features___entity_attention_1_1_sphere_i_i___n_p_c_features___entity_attention___on_update_live.html", null ]
    ] ],
    [ "SphereII_PoweredWorkstations", "d0/d7b/class_sphere_i_i___powered_workstations.html", "d0/d7b/class_sphere_i_i___powered_workstations" ],
    [ "SphereII_Progression", "d1/dcd/class_sphere_i_i___progression.html", "d1/dcd/class_sphere_i_i___progression" ],
    [ "SphereII_QuickLoad", "da/dcd/class_sphere_i_i___quick_load.html", [
      [ "SphereII_Main_Menu_AutoClick", "de/dcd/class_sphere_i_i___quick_load_1_1_sphere_i_i___main___menu___auto_click.html", null ],
      [ "SphereII_XUIC_NewContinueGame", "db/dd0/class_sphere_i_i___quick_load_1_1_sphere_i_i___x_u_i_c___new_continue_game.html", null ]
    ] ],
    [ "SphereII_RandomDeathSpawn", "d8/d89/class_sphere_i_i___random_death_spawn.html", [
      [ "SphereII_EntityAlive_OnEntityDeath", "df/dac/class_sphere_i_i___random_death_spawn_1_1_sphere_i_i___entity_alive___on_entity_death.html", null ]
    ] ],
    [ "SphereII_RandomSize", "d5/d89/class_sphere_i_i___random_size.html", "d5/d89/class_sphere_i_i___random_size" ],
    [ "SphereII_RemoveTraderProtection", "d5/d54/class_sphere_i_i___remove_trader_protection.html", "d5/d54/class_sphere_i_i___remove_trader_protection" ],
    [ "SphereII_SoundsFromXML", "da/d46/class_sphere_i_i___sounds_from_x_m_l.html", null ],
    [ "SphereII_TileEntityAlwaysActive", "d4/d02/class_sphere_i_i___tile_entity_always_active.html", "d4/d02/class_sphere_i_i___tile_entity_always_active" ],
    [ "SphereII_Transmogrifier", "d0/d04/class_sphere_i_i___transmogrifier.html", "d0/d04/class_sphere_i_i___transmogrifier" ],
    [ "SphereII_UMATweaks", "d1/d63/class_sphere_i_i___u_m_a_tweaks.html", "d1/d63/class_sphere_i_i___u_m_a_tweaks" ],
    [ "SphereII_WinterProject", "dc/d21/class_sphere_i_i___winter_project.html", [
      [ "SphereII_WinterProject_Init", "d4/d7b/class_sphere_i_i___winter_project_1_1_sphere_i_i___winter_project___init.html", "d4/d7b/class_sphere_i_i___winter_project_1_1_sphere_i_i___winter_project___init" ],
      [ "SphereII_WinterProject_LoadBlockData", "dd/d36/class_sphere_i_i___winter_project_1_1_sphere_i_i___winter_project___load_block_data.html", null ],
      [ "SphereII_WinterProject_Prefab", "d1/d1e/class_sphere_i_i___winter_project_1_1_sphere_i_i___winter_project___prefab.html", null ],
      [ "SphereII_WinterProject_Prefab_LoadXMLData", "d9/db1/class_sphere_i_i___winter_project_1_1_sphere_i_i___winter_project___prefab___load_x_m_l_data.html", null ],
      [ "SphereII_WinterProject_Prefab_Prefix", "d4/dde/class_sphere_i_i___winter_project_1_1_sphere_i_i___winter_project___prefab___prefix.html", null ],
      [ "SphereII_WinterProject_Prefab_Prefix_CopyBlocksIntoChunkNoEntities", "df/d69/class_sphere_i_i___winter_project_1_1_sphere_i_i___winter_project___prefab___prefix___copy_blocks_into_chunk_no_entities.html", null ],
      [ "SphereII_WinterProject_PrefabInstance", "d8/de8/class_sphere_i_i___winter_project_1_1_sphere_i_i___winter_project___prefab_instance.html", null ],
      [ "SphereII_WinterProject_PrefabInstance_CopyIntoChunk", "d6/dcf/class_sphere_i_i___winter_project_1_1_sphere_i_i___winter_project___prefab_instance___copy_into_chunk.html", null ]
    ] ],
    [ "SphereII_XML_Debugging", "d3/d4b/class_sphere_i_i___x_m_l___debugging.html", "d3/d4b/class_sphere_i_i___x_m_l___debugging" ],
    [ "SphereII_XPIconRemover", "da/df0/class_sphere_i_i___x_p_icon_remover.html", null ],
    [ "SphereII_XuiC_TargetBar", "d5/d8f/class_sphere_i_i___xui_c___target_bar.html", "d5/d8f/class_sphere_i_i___xui_c___target_bar" ],
    [ "SphereIICore_Init", "de/d40/class_sphere_i_i_core___init.html", "de/d40/class_sphere_i_i_core___init" ],
    [ "SphereIIQuickContinue_Init", "d2/d1b/class_sphere_i_i_quick_continue___init.html", "d2/d1b/class_sphere_i_i_quick_continue___init" ],
    [ "SphereIIToggleCapsLock", "d3/d04/class_sphere_i_i_toggle_caps_lock.html", null ],
    [ "TileEntityPoweredWorkstationSDX", "d1/d1b/class_tile_entity_powered_workstation_s_d_x.html", "d1/d1b/class_tile_entity_powered_workstation_s_d_x" ],
    [ "XUiC_CharacterFrameWindowSDX", "d2/dc0/class_x_ui_c___character_frame_window_s_d_x.html", "d2/dc0/class_x_ui_c___character_frame_window_s_d_x" ],
    [ "XUiC_DialogHireInformationSDX", "df/d79/class_x_ui_c___dialog_hire_information_s_d_x.html", "df/d79/class_x_ui_c___dialog_hire_information_s_d_x" ],
    [ "XUiC_DialogRespondentNameSDX", "d2/d70/class_x_ui_c___dialog_respondent_name_s_d_x.html", "d2/d70/class_x_ui_c___dialog_respondent_name_s_d_x" ],
    [ "XUiC_EntityInformationPanelSDX", "df/d1f/class_x_ui_c___entity_information_panel_s_d_x.html", "df/d1f/class_x_ui_c___entity_information_panel_s_d_x" ],
    [ "XUiC_HireInformationPopupSDX", "d6/d9a/class_x_ui_c___hire_information_popup_s_d_x.html", "d6/d9a/class_x_ui_c___hire_information_popup_s_d_x" ],
    [ "XUiC_JoinInformationPopupSDX", "da/d90/class_x_ui_c___join_information_popup_s_d_x.html", "da/d90/class_x_ui_c___join_information_popup_s_d_x" ]
];