var _entity_n_p_c_make_vulnerable_8cs =
[
    [ "Harmony.NPCFeatures.EntityNPCMakeVulnerable.SCoreRemoveTraderProtectionPostInit", "class_harmony_1_1_n_p_c_features_1_1_entity_n_p_c_make_vulnerable_1_1_s_core_remove_trader_protection_post_init.html", null ],
    [ "Harmony.NPCFeatures.EntityNPCMakeVulnerable.SCoreRemoveTraderProtectionProcessDamageResponse", "class_harmony_1_1_n_p_c_features_1_1_entity_n_p_c_make_vulnerable_1_1_s_core_remove_trader_protection_process_damage_response.html", null ],
    [ "Harmony.NPCFeatures.EntityNPCMakeVulnerable.SCoreRemoveTraderProtectionDamageEntity", "class_harmony_1_1_n_p_c_features_1_1_entity_n_p_c_make_vulnerable_1_1_s_core_remove_trader_protection_damage_entity.html", null ]
];