// 
// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// 

using System.Reflection;

[assembly: AssemblyVersion("20.0.1072.715")]
[assembly: AssemblyFileVersion("20.0.1072.715")]
